# Generated by Django 3.2.14 on 2022-08-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="backend/default.png", upload_to="profile_pics"
            ),
        ),
    ]
