# Generated by Django 3.2.14 on 2022-08-20 16:00

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.ImageField(
                upload_to="media/book/", validators=[blog.validators.validate_cover]
            ),
        ),
    ]
